import React, { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Compass, Crosshair, Filter, LocateFixed, MapPin, Search, Sparkles, AlertCircle, RotateCcw } from 'lucide-react';
import { placesApi } from '../services/api';
import PlaceCard from '../components/trip/PlaceCard';
import LoadingSpinner from '../components/common/LoadingSpinner';

const LOCATION_ERRORS = { 1: 'Location access was not allowed. You can enter a location manually.', 2: 'Unable to determine your location. Please try again or enter a location manually.', 3: 'Location request timed out. Please try again or enter a location manually.' };

export default function RecommendedPlaces() {
  const navigate = useNavigate();
  const [places, setPlaces] = useState([]); const [cities, setCities] = useState([]); const [categories, setCategories] = useState([]);
  const [loading, setLoading] = useState(true); const [nearbyLoading, setNearbyLoading] = useState(false);
  const [searchQuery, setSearchQuery] = useState(''); const [selectedCity, setSelectedCity] = useState(''); const [selectedCategory, setSelectedCategory] = useState('');
  const [manualLocation, setManualLocation] = useState(''); const [radius, setRadius] = useState(5); const [nearby, setNearby] = useState([]);
  const [locationLabel, setLocationLabel] = useState(''); const [locationError, setLocationError] = useState('');
  const [selected, setSelected] = useState(() => JSON.parse(sessionStorage.getItem('travelwise_selected_places') || '[]'));

  useEffect(() => { (async () => { try { const [p, c, cat] = await Promise.all([placesApi.getPlaces(), placesApi.getCities(), placesApi.getCategories()]); setPlaces(p.data); setCities(c.data); setCategories(cat.data); } catch { setLocationError('Places could not be loaded. Check that the TravelWise backend is running.'); } finally { setLoading(false); } })(); }, []);
  useEffect(() => { sessionStorage.setItem('travelwise_selected_places', JSON.stringify(selected)); }, [selected]);
  const filteredPlaces = useMemo(() => places.filter((place) => { const query = searchQuery.toLowerCase(); return (!query || [place.name, place.description, place.city].some((value) => value?.toLowerCase().includes(query))) && (!selectedCity || place.city === selectedCity) && (!selectedCategory || place.category === selectedCategory); }), [places, searchQuery, selectedCity, selectedCategory]);
  const shownPlaces = nearby.length ? nearby : filteredPlaces;
  const toggleSelected = (place) => setSelected((current) => current.some((item) => item.place_id === (place.place_id || `curated:${place.id}`)) ? current.filter((item) => item.place_id !== (place.place_id || `curated:${place.id}`)) : [...current, { ...place, place_id: place.place_id || `curated:${place.id}` }]);
  const findNearby = async (coords, label) => { setNearbyLoading(true); setLocationError(''); try { const response = await placesApi.getNearby({ latitude: coords.latitude, longitude: coords.longitude, radius_km: Number(radius), limit: 20 }); setNearby(response.data); setLocationLabel(label); } catch (error) { setNearby([]); setLocationError(error.response?.data?.detail || 'Unable to find nearby places right now. Please try again.'); } finally { setNearbyLoading(false); } };
  const useCurrentLocation = () => { setLocationError(''); if (!navigator.geolocation) { setLocationError('Location services are not supported by this browser.'); return; } setNearbyLoading(true); navigator.geolocation.getCurrentPosition((position) => findNearby({ latitude: position.coords.latitude, longitude: position.coords.longitude }, 'Your current location'), (error) => { setNearbyLoading(false); setLocationError(LOCATION_ERRORS[error.code] || 'Unable to determine your location. Please try again or enter a location manually.'); }, { enableHighAccuracy: true, timeout: 10000, maximumAge: 300000 }); };
  const searchManualLocation = async (event) => { event.preventDefault(); if (!manualLocation.trim()) return; setNearbyLoading(true); setLocationError(''); try { const result = await placesApi.geocode(manualLocation); await findNearby(result.data, result.data.label); } catch (error) { setNearbyLoading(false); setLocationError(error.response?.data?.detail || 'Unable to find that location.'); } };
  const continueToPlanner = () => { const curated = selected.filter((place) => place.place_id.startsWith('curated:')).map((place) => place.place_id.replace('curated:', '')); const city = selected[0]?.city || selectedCity; navigate(`/create-trip?${new URLSearchParams({ ...(city ? { city } : {}), ...(curated.length ? { selected: curated.join(',') } : {}) })}`); };

  return <div className="min-h-screen bg-slate-50 py-8 px-4 sm:px-6 lg:px-8"><div className="max-w-7xl mx-auto space-y-7">
    <header className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><p className="inline-flex items-center gap-2 text-xs font-bold text-brand-600 uppercase tracking-wider"><Compass className="w-4 h-4" /> Curated places & live discovery</p><h1 className="mt-2 text-3xl font-extrabold text-slate-900 font-heading">Explore places that fit your trip</h1><p className="text-sm text-slate-500 mt-1">Browse freely, then sign in only when you are ready to build and save an itinerary.</p></div><button onClick={continueToPlanner} className="px-5 py-3 rounded-xl bg-brand-600 hover:bg-brand-700 text-white font-semibold text-sm shadow-md flex items-center gap-2"><Sparkles className="w-4 h-4" /> Generate itinerary{selected.length ? ` (${selected.length})` : ''}</button></header>
    <section className="rounded-2xl bg-slate-900 text-white p-5 sm:p-6 shadow-lg"><div className="flex flex-col lg:flex-row lg:items-end gap-5"><div className="flex-1"><p className="text-xs font-bold uppercase tracking-widest text-brand-300">Discover places near you</p><h2 className="text-xl font-bold font-heading mt-1">Use your location, or search a city</h2><p className="text-sm text-slate-300 mt-1">Your coordinates are used only for this search and are never saved.</p></div><div className="flex flex-col sm:flex-row gap-2"><button onClick={useCurrentLocation} disabled={nearbyLoading} className="px-4 py-2.5 rounded-xl bg-white text-slate-900 text-sm font-bold hover:bg-brand-50 disabled:opacity-60 flex items-center justify-center gap-2"><LocateFixed className="w-4 h-4 text-brand-600" />{nearbyLoading ? 'Getting your location…' : 'Use My Current Location'}</button><form onSubmit={searchManualLocation} className="flex gap-2"><input value={manualLocation} onChange={(e) => setManualLocation(e.target.value)} placeholder="Enter a city or destination" className="min-w-0 w-full sm:w-52 px-3 py-2.5 rounded-xl text-sm text-slate-900" /><button className="px-3 rounded-xl bg-brand-500 hover:bg-brand-400" aria-label="Search location"><Search className="w-4 h-4" /></button></form></div></div><div className="mt-5 flex flex-wrap items-center gap-3"><label className="text-xs text-slate-300">Search radius</label><select value={radius} onChange={(e) => setRadius(e.target.value)} className="text-sm text-slate-900 rounded-lg px-3 py-2">{[1, 5, 10, 25, 50].map((value) => <option key={value} value={value}>{value} km</option>)}</select>{locationLabel && <span className="inline-flex items-center gap-1 text-xs bg-white/10 rounded-lg px-3 py-2"><MapPin className="w-3.5 h-3.5 text-brand-300" /> {locationLabel} · within {radius} km</span>}</div></section>
    {locationError && <div className="flex gap-2 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><AlertCircle className="w-5 h-5 shrink-0" />{locationError}</div>}
    <section className="bg-white p-4 sm:p-5 rounded-2xl border border-slate-200 shadow-sm"><div className="grid grid-cols-1 md:grid-cols-3 gap-3"><label className="relative"><Search className="absolute left-3.5 top-3 w-4 h-4 text-slate-400" /><input value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} placeholder="Search sights, food, beaches…" className="w-full pl-10 pr-3 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm" /></label><label className="relative"><MapPin className="absolute left-3.5 top-3 w-4 h-4 text-slate-400" /><select value={selectedCity} onChange={(e) => { setSelectedCity(e.target.value); setNearby([]); }} className="w-full pl-10 pr-3 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm"><option value="">All cities ({cities.length})</option>{cities.map((city) => <option key={city}>{city}</option>)}</select></label><label className="relative"><Filter className="absolute left-3.5 top-3 w-4 h-4 text-slate-400" /><select value={selectedCategory} onChange={(e) => setSelectedCategory(e.target.value)} className="w-full pl-10 pr-3 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm"><option value="">All categories ({categories.length})</option>{categories.map((category) => <option key={category}>{category}</option>)}</select></label></div></section>
    {loading || nearbyLoading ? <LoadingSpinner text={nearbyLoading ? 'Finding places with real coordinates…' : 'Loading TravelWise places…'} /> : shownPlaces.length ? <section><div className="flex justify-between items-center mb-4"><p className="text-sm font-semibold text-slate-600">{nearby.length ? `Nearby places, nearest first (${shownPlaces.length})` : `${shownPlaces.length} places to explore`}</p>{nearby.length > 0 && <button onClick={() => { setNearby([]); setLocationLabel(''); }} className="text-xs font-semibold text-brand-700">Browse all curated places</button>}</div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">{shownPlaces.map((place) => <PlaceCard key={place.place_id || place.id} place={place} showSelectBtn isSelected={selected.some((item) => item.place_id === (place.place_id || `curated:${place.id}`))} onSelect={toggleSelected} />)}</div></section> : <section className="text-center py-16 bg-white rounded-2xl border border-slate-200"><Crosshair className="w-10 h-10 text-slate-300 mx-auto mb-3" /><h3 className="font-bold">No places found within {radius} km.</h3><p className="text-sm text-slate-500 mt-1">Increase the search radius or try another location.</p><button onClick={() => { setRadius(25); setNearby([]); setSearchQuery(''); setSelectedCity(''); setSelectedCategory(''); }} className="mt-4 inline-flex gap-2 items-center text-sm font-semibold text-brand-700"><RotateCcw className="w-4 h-4" /> Clear filters</button></section>}
  </div></div>;
}
