SAMPLE_PLACES = [
    # --- HYDERABAD & NEARBY ---
    {
        "name": "Golconda Fort",
        "description": "Magnificent 16th-century fortress known for its acoustic architecture, royal palaces, and panoramic sunset views over Hyderabad.",
        "city": "Hyderabad",
        "state": "Telangana",
        "address": "Ibrahim Bagh, Hyderabad",
        "latitude": 17.3833,
        "longitude": 78.4011,
        "category": "Historical",
        "estimated_duration_hours": 3.0,
        "estimated_cost": 80.0,
        "best_visiting_time": "Morning",
        "suitable_interests": "History,Sightseeing,Architecture,Photography",
        "rating": 4.6,
        "image_url": "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80",
        "opening_time": "09:00",
        "closing_time": "17:30"
    },
    {
        "name": "Charminar & Laad Bazaar",
        "description": "The quintessential landmark of Hyderabad built in 1591, surrounded by the bustling Laad Bazaar famous for bangles, pearls, and street delicacies.",
        "city": "Hyderabad",
        "state": "Telangana",
        "address": "Charminar Rd, Char Kaman, Ghansi Bazaar, Hyderabad",
        "latitude": 17.3616,
        "longitude": 78.4747,
        "category": "Culture",
        "estimated_duration_hours": 2.0,
        "estimated_cost": 50.0,
        "best_visiting_time": "Evening",
        "suitable_interests": "Culture,Shopping,Food,History,Sightseeing",
        "rating": 4.5,
        "image_url": "https://images.unsplash.com/photo-1608958435020-e8a7109ba809?auto=format&fit=crop&w=800&q=80",
        "opening_time": "09:30",
        "closing_time": "19:00"
    },
    {
        "name": "Hussain Sagar Lake & Buddha Statue",
        "description": "Heart-shaped lake featuring the world's tallest monolithic Buddha statue, scenic boat rides, and the vibrant Necklace Road promenade.",
        "city": "Hyderabad",
        "state": "Telangana",
        "address": "Tank Bund Rd, Hussain Sagar, Hyderabad",
        "latitude": 17.4239,
        "longitude": 78.4738,
        "category": "Nature",
        "estimated_duration_hours": 2.0,
        "estimated_cost": 100.0,
        "best_visiting_time": "Sunset",
        "suitable_interests": "Nature,Sightseeing,Boating,Relaxation,Sunset",
        "rating": 4.4,
        "image_url": "https://images.unsplash.com/photo-1572953109213-3be62398eb95?auto=format&fit=crop&w=800&q=80",
        "opening_time": "08:00",
        "closing_time": "22:00"
    },
    {
        "name": "Salar Jung Museum",
        "description": "One of India's premier national museums housing an unmatched one-man collection of antique sculptures, European clocks, and Mughal miniatures.",
        "city": "Hyderabad",
        "state": "Telangana",
        "address": "Daru-shifa, Hyderabad",
        "latitude": 17.3713,
        "longitude": 78.4804,
        "category": "Historical",
        "estimated_duration_hours": 2.5,
        "estimated_cost": 50.0,
        "best_visiting_time": "Morning",
        "suitable_interests": "History,Art,Culture,Museum,Sightseeing",
        "rating": 4.6,
        "image_url": "https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?auto=format&fit=crop&w=800&q=80",
        "opening_time": "10:00",
        "closing_time": "17:00"
    },
    {
        "name": "Durgam Cheruvu Lake & Cable Bridge",
        "description": "Secret lake nestled between granite hills featuring a striking illuminated suspension cable bridge, lakeside dining, and evening walking decks.",
        "city": "Hyderabad",
        "state": "Telangana",
        "address": "Hitech City, Madhapur, Hyderabad",
        "latitude": 17.4363,
        "longitude": 78.3842,
        "category": "Nature",
        "estimated_duration_hours": 2.0,
        "estimated_cost": 0.0,
        "best_visiting_time": "Sunset",
        "suitable_interests": "Nature,Sightseeing,Food,Relaxation,Photography",
        "rating": 4.5,
        "image_url": "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80",
        "opening_time": "06:00",
        "closing_time": "22:00"
    },
    {
        "name": "Shilparamam Arts & Crafts Village",
        "description": "Tribute to Indian handicrafts, traditional folk performances, artisanal pottery, night markets, and authentic regional cuisines.",
        "city": "Hyderabad",
        "state": "Telangana",
        "address": "Hi Tech City Main Rd, Madhapur, Hyderabad",
        "latitude": 17.4526,
        "longitude": 78.3776,
        "category": "Culture",
        "estimated_duration_hours": 2.5,
        "estimated_cost": 60.0,
        "best_visiting_time": "Evening",
        "suitable_interests": "Culture,Shopping,Food,Handicrafts,Family",
        "rating": 4.3,
        "image_url": "https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?auto=format&fit=crop&w=800&q=80",
        "opening_time": "10:30",
        "closing_time": "20:30"
    },
    {
        "name": "Chowmahalla Palace",
        "description": "Opulent seat of the Asaf Jahi dynasty, famous for grand chandelier-lit Durbar halls, vintage car collections, and verdant courtyards.",
        "city": "Hyderabad",
        "state": "Telangana",
        "address": "Motigall, Khilwat, Hyderabad",
        "latitude": 17.3578,
        "longitude": 78.4717,
        "category": "Historical",
        "estimated_duration_hours": 2.0,
        "estimated_cost": 100.0,
        "best_visiting_time": "Afternoon",
        "suitable_interests": "History,Architecture,Heritage,Photography",
        "rating": 4.6,
        "image_url": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80",
        "opening_time": "10:00",
        "closing_time": "17:00"
    },
    {
        "name": "Birla Mandir",
        "description": "Stunning white Rajasthani marble temple perched on a 280-foot high hillock overlooking the twin cities and Hussain Sagar lake.",
        "city": "Hyderabad",
        "state": "Telangana",
        "address": "Hill Fort Rd, Ambedkar Colony, Khairtabad, Hyderabad",
        "latitude": 17.4062,
        "longitude": 78.4691,
        "category": "Culture",
        "estimated_duration_hours": 1.5,
        "estimated_cost": 0.0,
        "best_visiting_time": "Sunset",
        "suitable_interests": "Culture,Sightseeing,Peace,Sunset",
        "rating": 4.7,
        "image_url": "https://images.unsplash.com/photo-1545128485-c400e7702796?auto=format&fit=crop&w=800&q=80",
        "opening_time": "07:00",
        "closing_time": "21:00"
    },
    {
        "name": "Famous Hyderabadi Biryani & Food Trail",
        "description": "Indulge in authentic Dum Biryani, double ka meetha, Irani chai, and Osmania biscuits at iconic culinary institutions.",
        "city": "Hyderabad",
        "state": "Telangana",
        "address": "Secunderabad / Old City, Hyderabad",
        "latitude": 17.4416,
        "longitude": 78.4883,
        "category": "Food",
        "estimated_duration_hours": 1.5,
        "estimated_cost": 400.0,
        "best_visiting_time": "Afternoon",
        "suitable_interests": "Food,Culinary,Culture,Dining",
        "rating": 4.8,
        "image_url": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80",
        "opening_time": "11:30",
        "closing_time": "23:00"
    },
    {
        "name": "KBR National Park",
        "description": "Vast natural urban forest sanctuary with peacocks, rich avifauna, jogging trails, and clean green breathing space in Jubilee Hills.",
        "city": "Hyderabad",
        "state": "Telangana",
        "address": "Jubilee Hills, Hyderabad",
        "latitude": 17.4244,
        "longitude": 78.4231,
        "category": "Nature",
        "estimated_duration_hours": 2.0,
        "estimated_cost": 40.0,
        "best_visiting_time": "Morning",
        "suitable_interests": "Nature,Walking,Wellness,Birdwatching",
        "rating": 4.5,
        "image_url": "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80",
        "opening_time": "05:30",
        "closing_time": "18:00"
    },
    {
        "name": "Ananthagiri Hills & Trekking Forest",
        "description": "Scenic hill station 80 km from Hyderabad offering dense coffee estates, ancient temples, tranquil trekking trails, and viewpoints.",
        "city": "Hyderabad",
        "state": "Telangana",
        "address": "Vikarabad, Telangana",
        "latitude": 17.3117,
        "longitude": 77.8687,
        "category": "Adventure",
        "estimated_duration_hours": 4.0,
        "estimated_cost": 150.0,
        "best_visiting_time": "Morning",
        "suitable_interests": "Adventure,Nature,Trekking,Sightseeing,Peace",
        "rating": 4.5,
        "image_url": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80",
        "opening_time": "06:00",
        "closing_time": "18:00"
    },
    {
        "name": "Bhongir Fort & Rock Climbing",
        "description": "Mighty monolithic egg-shaped rock fortress with an exhilarating uphill climb and panoramic countryside views 50 km from Hyderabad.",
        "city": "Hyderabad",
        "state": "Telangana",
        "address": "Bhuvanagiri, Telangana",
        "latitude": 17.5108,
        "longitude": 78.8894,
        "category": "Adventure",
        "estimated_duration_hours": 3.0,
        "estimated_cost": 25.0,
        "best_visiting_time": "Morning",
        "suitable_interests": "Adventure,History,Trekking,Sightseeing",
        "rating": 4.4,
        "image_url": "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=800&q=80",
        "opening_time": "08:00",
        "closing_time": "17:00"
    },

    # --- GOA ---
    {
        "name": "Baga Beach & Water Sports",
        "description": "Lively coastal haven famous for jet skiing, parasailing, dolphin cruises, and buzzing beach shacks.",
        "city": "Goa",
        "state": "Goa",
        "address": "Baga, North Goa",
        "latitude": 15.5553,
        "longitude": 73.7517,
        "category": "Beach",
        "estimated_duration_hours": 3.5,
        "estimated_cost": 350.0,
        "best_visiting_time": "Afternoon",
        "suitable_interests": "Beach,Adventure,Water Sports,Food,Relaxation",
        "rating": 4.6,
        "image_url": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80",
        "opening_time": "06:00",
        "closing_time": "23:00"
    },
    {
        "name": "Fort Aguada & Lighthouse",
        "description": "Well-preserved 17th-century Portuguese fortress overlooking the Arabian Sea, featuring a historic 4-storey lighthouse.",
        "city": "Goa",
        "state": "Goa",
        "address": "Sinquerim, Candolim, Goa",
        "latitude": 15.4926,
        "longitude": 73.7737,
        "category": "Historical",
        "estimated_duration_hours": 2.0,
        "estimated_cost": 50.0,
        "best_visiting_time": "Sunset",
        "suitable_interests": "History,Sightseeing,Photography,Sunset,Beach",
        "rating": 4.5,
        "image_url": "https://images.unsplash.com/photo-1587974928442-77dc3e0dba72?auto=format&fit=crop&w=800&q=80",
        "opening_time": "09:30",
        "closing_time": "18:00"
    },
    {
        "name": "Fontainhas Latin Quarter",
        "description": "Heritage Portuguese colonial quarter filled with colorful yellow-and-blue villas, art galleries, and quaint cafes.",
        "city": "Goa",
        "state": "Goa",
        "address": "Panaji, Goa",
        "latitude": 15.4989,
        "longitude": 73.8315,
        "category": "Culture",
        "estimated_duration_hours": 2.0,
        "estimated_cost": 0.0,
        "best_visiting_time": "Morning",
        "suitable_interests": "Culture,Architecture,Photography,Food,History",
        "rating": 4.7,
        "image_url": "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
        "opening_time": "08:00",
        "closing_time": "20:00"
    },
    {
        "name": "Palolem Beach & Kayaking",
        "description": "Crescent-shaped serene beach framed by swaying coconut palms, gentle shallow waters ideal for kayaking and relaxation.",
        "city": "Goa",
        "state": "Goa",
        "address": "Canacona, South Goa",
        "latitude": 15.0100,
        "longitude": 74.0232,
        "category": "Beach",
        "estimated_duration_hours": 3.0,
        "estimated_cost": 200.0,
        "best_visiting_time": "Sunset",
        "suitable_interests": "Beach,Nature,Kayaking,Relaxation,Sunset",
        "rating": 4.7,
        "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
        "opening_time": "06:00",
        "closing_time": "22:00"
    },

    # --- BENGALURU ---
    {
        "name": "Lalbagh Botanical Garden",
        "description": "Historic 240-acre botanical haven founded by Hyder Ali, featuring century-old trees, a glass house modeled on London's Crystal Palace, and serene lakes.",
        "city": "Bengaluru",
        "state": "Karnataka",
        "address": "Mavalli, Bengaluru",
        "latitude": 12.9507,
        "longitude": 77.5848,
        "category": "Nature",
        "estimated_duration_hours": 2.0,
        "estimated_cost": 30.0,
        "best_visiting_time": "Morning",
        "suitable_interests": "Nature,Walking,Photography,Relaxation",
        "rating": 4.6,
        "image_url": "https://images.unsplash.com/photo-1588691515220-bb620a2e5d76?auto=format&fit=crop&w=800&q=80",
        "opening_time": "06:00",
        "closing_time": "19:00"
    },
    {
        "name": "Bangalore Palace",
        "description": "Tudor-revival architectural marvel with turreted parapets, vintage wood carvings, royal artifacts, and grand banquet halls.",
        "city": "Bengaluru",
        "state": "Karnataka",
        "address": "Vasanth Nagar, Bengaluru",
        "latitude": 12.9988,
        "longitude": 77.5921,
        "category": "Historical",
        "estimated_duration_hours": 2.5,
        "estimated_cost": 250.0,
        "best_visiting_time": "Afternoon",
        "suitable_interests": "History,Architecture,Culture,Sightseeing",
        "rating": 4.4,
        "image_url": "https://images.unsplash.com/photo-1600100397608-f010f443b784?auto=format&fit=crop&w=800&q=80",
        "opening_time": "10:00",
        "closing_time": "17:30"
    },
    {
        "name": "Nandi Hills Sunrise Viewpoint",
        "description": "Breathtaking hill fortress 60 km from Bengaluru famous for misty clouds above valleys, Tipu Sultan's summer residence, and hiking paths.",
        "city": "Bengaluru",
        "state": "Karnataka",
        "address": "Chikkaballapur, Karnataka",
        "latitude": 13.3702,
        "longitude": 77.6835,
        "category": "Adventure",
        "estimated_duration_hours": 3.5,
        "estimated_cost": 20.0,
        "best_visiting_time": "Morning",
        "suitable_interests": "Adventure,Nature,Sunrise,Trekking,Photography",
        "rating": 4.5,
        "image_url": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
        "opening_time": "06:00",
        "closing_time": "18:00"
    },

    # --- JAIPUR ---
    {
        "name": "Amber Fort & Palace",
        "description": "Majestic hilltop fortress made of yellow and pink sandstone, famous for the glittering Sheesh Mahal mirror palace and Maota lake views.",
        "city": "Jaipur",
        "state": "Rajasthan",
        "address": "Devisinghpura, Amer, Jaipur",
        "latitude": 26.9855,
        "longitude": 75.8513,
        "category": "Historical",
        "estimated_duration_hours": 3.0,
        "estimated_cost": 100.0,
        "best_visiting_time": "Morning",
        "suitable_interests": "History,Heritage,Architecture,Sightseeing,Culture",
        "rating": 4.7,
        "image_url": "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=800&q=80",
        "opening_time": "08:00",
        "closing_time": "17:30"
    },
    {
        "name": "Hawa Mahal (Palace of Winds)",
        "description": "Iconic five-story honeycomb façade featuring 953 ornate lattice windows designed for royal women to observe street festivals unnoticed.",
        "city": "Jaipur",
        "state": "Rajasthan",
        "address": "Hawa Mahal Rd, Badi Choupad, Jaipur",
        "latitude": 26.9239,
        "longitude": 75.8267,
        "category": "Historical",
        "estimated_duration_hours": 1.5,
        "estimated_cost": 50.0,
        "best_visiting_time": "Morning",
        "suitable_interests": "History,Architecture,Photography,Culture",
        "rating": 4.6,
        "image_url": "https://images.unsplash.com/photo-1609137144822-45e054ee461e?auto=format&fit=crop&w=800&q=80",
        "opening_time": "09:00",
        "closing_time": "17:00"
    },
    {
        "name": "Nahargarh Fort Sunset Point",
        "description": "Perched on the rugged Aravalli ridge, offering the most dramatic panoramic sunset viewpoint overlooking the entire pink city of Jaipur.",
        "city": "Jaipur",
        "state": "Rajasthan",
        "address": "Krishna Nagar, Brahampuri, Jaipur",
        "latitude": 26.9373,
        "longitude": 75.8156,
        "category": "Historical",
        "estimated_duration_hours": 2.0,
        "estimated_cost": 50.0,
        "best_visiting_time": "Sunset",
        "suitable_interests": "History,Sightseeing,Sunset,Photography,Food",
        "rating": 4.7,
        "image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80",
        "opening_time": "10:00",
        "closing_time": "18:00"
    },

    # --- MUNNAR & KERALA ---
    {
        "name": "Eravikulam National Park",
        "description": "High-altitude sanctuary home to the endangered Nilgiri Tahr, rolling grasslands, and misty Shola forests in the Western Ghats.",
        "city": "Munnar",
        "state": "Kerala",
        "address": "Kannan Devan Hills, Munnar",
        "latitude": 10.2016,
        "longitude": 77.0467,
        "category": "Nature",
        "estimated_duration_hours": 3.0,
        "estimated_cost": 200.0,
        "best_visiting_time": "Morning",
        "suitable_interests": "Nature,Wildlife,Trekking,Photography,Sightseeing",
        "rating": 4.7,
        "image_url": "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80",
        "opening_time": "07:30",
        "closing_time": "16:00"
    },
    {
        "name": "Mattupetty Dam & Lake Boating",
        "description": "Concrete gravity dam surrounded by lush green tea hills and pine trees, with speedboat rides and frequent wild elephant sightings.",
        "city": "Munnar",
        "state": "Kerala",
        "address": "Mattupetty, Munnar",
        "latitude": 10.1060,
        "longitude": 77.1235,
        "category": "Nature",
        "estimated_duration_hours": 2.0,
        "estimated_cost": 100.0,
        "best_visiting_time": "Afternoon",
        "suitable_interests": "Nature,Boating,Sightseeing,Relaxation",
        "rating": 4.4,
        "image_url": "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80",
        "opening_time": "09:30",
        "closing_time": "17:00"
    }
]
