SAMPLE_PLACES = [
    # --- HYDERABAD ---
    {
        "name": "Charminar & Laad Bazaar",
        "description": "The quintessential 1591 monument of Hyderabad with four grand minarets, surrounded by the vibrant pearl and bangle markets of Old City.",
        "city": "Hyderabad",
        "state": "Telangana",
        "address": "Charminar Rd, Ghansi Bazaar, Hyderabad",
        "latitude": 17.3616,
        "longitude": 78.4747,
        "category": "Culture",
        "estimated_duration_hours": 2.0,
        "estimated_cost": 50.0,
        "best_visiting_time": "Evening",
        "suitable_interests": "Culture,Shopping,Food,History,Sightseeing",
        "rating": 4.7,
        "image_url": "https://images.unsplash.com/photo-1572445271230-a78b5944a659?w=800&auto=format&fit=crop&q=80",
        "opening_time": "09:30",
        "closing_time": "19:00"
    },
    {
        "name": "Golconda Fort",
        "description": "Magnificent medieval hilltop fortress known for its acoustic engineering, royal palaces, acoustic clapping portico, and panoramic sunset views.",
        "city": "Hyderabad",
        "state": "Telangana",
        "address": "Ibrahim Bagh, Hyderabad",
        "latitude": 17.3833,
        "longitude": 78.4011,
        "category": "Historical",
        "estimated_duration_hours": 3.0,
        "estimated_cost": 80.0,
        "best_visiting_time": "Morning",
        "suitable_interests": "History,Sightseeing,Architecture,Photography",
        "rating": 4.6,
        "image_url": "https://images.unsplash.com/photo-1617854818583-09e7f077a156?w=800&auto=format&fit=crop&q=80",
        "opening_time": "09:00",
        "closing_time": "17:30"
    },
    {
        "name": "Hussain Sagar Lake & Buddha Statue",
        "description": "Heart-shaped historic lake featuring the world's tallest monolithic Buddha statue standing in the center, with scenic boat cruises and waterfront promenade.",
        "city": "Hyderabad",
        "state": "Telangana",
        "address": "Tank Bund Rd, Hussain Sagar, Hyderabad",
        "latitude": 17.4239,
        "longitude": 78.4738,
        "category": "Nature",
        "estimated_duration_hours": 2.0,
        "estimated_cost": 100.0,
        "best_visiting_time": "Sunset",
        "suitable_interests": "Nature,Sightseeing,Boating,Relaxation,Sunset",
        "rating": 4.5,
        "image_url": "https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?w=800&auto=format&fit=crop&q=80",
        "opening_time": "08:00",
        "closing_time": "22:00"
    },
    {
        "name": "Salar Jung Museum",
        "description": "Premier national art and history museum housing one of the largest private antique collections of European clocks, jade, and Indian sculptures.",
        "city": "Hyderabad",
        "state": "Telangana",
        "address": "Daru-shifa, Hyderabad",
        "latitude": 17.3713,
        "longitude": 78.4804,
        "category": "Historical",
        "estimated_duration_hours": 2.5,
        "estimated_cost": 50.0,
        "best_visiting_time": "Morning",
        "suitable_interests": "History,Art,Culture,Museum,Sightseeing",
        "rating": 4.6,
        "image_url": "https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?w=800&auto=format&fit=crop&q=80",
        "opening_time": "10:00",
        "closing_time": "17:00"
    },
    {
        "name": "Chowmahalla Palace",
        "description": "Opulent palace complex of the Nizams of Hyderabad, boasting majestic courtyards, grand chandelier-lit Durbar halls, and vintage vintage car exhibits.",
        "city": "Hyderabad",
        "state": "Telangana",
        "address": "Motigall, Khilwat, Hyderabad",
        "latitude": 17.3578,
        "longitude": 78.4717,
        "category": "Historical",
        "estimated_duration_hours": 2.0,
        "estimated_cost": 100.0,
        "best_visiting_time": "Afternoon",
        "suitable_interests": "History,Architecture,Heritage,Photography",
        "rating": 4.6,
        "image_url": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80",
        "opening_time": "10:00",
        "closing_time": "17:00"
    },
    {
        "name": "Birla Mandir",
        "description": "Pristine white marble temple perched atop a 280-foot high granite hillock, overlooking the twin cities and Hussain Sagar lake at sunset.",
        "city": "Hyderabad",
        "state": "Telangana",
        "address": "Hill Fort Rd, Khairtabad, Hyderabad",
        "latitude": 17.4062,
        "longitude": 78.4691,
        "category": "Culture",
        "estimated_duration_hours": 1.5,
        "estimated_cost": 0.0,
        "best_visiting_time": "Sunset",
        "suitable_interests": "Culture,Sightseeing,Peace,Sunset",
        "rating": 4.7,
        "image_url": "https://images.unsplash.com/photo-1545128485-c400e7702796?w=800&auto=format&fit=crop&q=80",
        "opening_time": "07:00",
        "closing_time": "21:00"
    },
    {
        "name": "Durgam Cheruvu & Cable Bridge",
        "description": "Tranquil freshwater lake nestled between rock formations, featuring an illuminated suspension cable bridge, lakeside cafes, and sunset boardwalks.",
        "city": "Hyderabad",
        "state": "Telangana",
        "address": "Madhapur, Hitech City, Hyderabad",
        "latitude": 17.4363,
        "longitude": 78.3842,
        "category": "Nature",
        "estimated_duration_hours": 2.0,
        "estimated_cost": 0.0,
        "best_visiting_time": "Sunset",
        "suitable_interests": "Nature,Sightseeing,Food,Relaxation,Photography",
        "rating": 4.5,
        "image_url": "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&auto=format&fit=crop&q=80",
        "opening_time": "06:00",
        "closing_time": "22:00"
    },
    {
        "name": "Hyderabadi Dum Biryani Trail",
        "description": "Authentic culinary journey through Hyderabad's legendary biryani hubs, Irani chai cafes, and famous royal desserts like double ka meetha.",
        "city": "Hyderabad",
        "state": "Telangana",
        "address": "Old City / Secunderabad, Hyderabad",
        "latitude": 17.4416,
        "longitude": 78.4883,
        "category": "Food",
        "estimated_duration_hours": 1.5,
        "estimated_cost": 400.0,
        "best_visiting_time": "Afternoon",
        "suitable_interests": "Food,Culinary,Culture,Dining",
        "rating": 4.8,
        "image_url": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=80",
        "opening_time": "11:30",
        "closing_time": "23:00"
    },

    # --- GOA ---
    {
        "name": "Baga Beach & Water Sports",
        "description": "Lively coastal haven in North Goa renowned for water skiing, parasailing, dolphin watching trips, beach shacks, and tropical sunsets.",
        "city": "Goa",
        "state": "Goa",
        "address": "Baga, North Goa",
        "latitude": 15.5553,
        "longitude": 73.7517,
        "category": "Beach",
        "estimated_duration_hours": 3.5,
        "estimated_cost": 350.0,
        "best_visiting_time": "Afternoon",
        "suitable_interests": "Beach,Adventure,Water Sports,Food,Relaxation",
        "rating": 4.6,
        "image_url": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80",
        "opening_time": "06:00",
        "closing_time": "23:00"
    },
    {
        "name": "Fort Aguada & Lighthouse",
        "description": "Well-preserved 17th-century Portuguese coastal fortress overlooking the Arabian Sea, housing a historic four-tier stone lighthouse.",
        "city": "Goa",
        "state": "Goa",
        "address": "Sinquerim, Candolim, Goa",
        "latitude": 15.4926,
        "longitude": 73.7737,
        "category": "Historical",
        "estimated_duration_hours": 2.0,
        "estimated_cost": 50.0,
        "best_visiting_time": "Sunset",
        "suitable_interests": "History,Sightseeing,Photography,Sunset,Beach",
        "rating": 4.5,
        "image_url": "https://images.unsplash.com/photo-1587974928442-77dc3e0dba72?w=800&auto=format&fit=crop&q=80",
        "opening_time": "09:30",
        "closing_time": "18:00"
    },
    {
        "name": "Palolem Beach & Kayaking",
        "description": "Crescent-shaped serene beach in South Goa framed by lush coconut groves, calm turquoise waters ideal for kayaking and peaceful strolls.",
        "city": "Goa",
        "state": "Goa",
        "address": "Canacona, South Goa",
        "latitude": 15.0100,
        "longitude": 74.0232,
        "category": "Beach",
        "estimated_duration_hours": 3.0,
        "estimated_cost": 200.0,
        "best_visiting_time": "Sunset",
        "suitable_interests": "Beach,Nature,Kayaking,Relaxation,Sunset",
        "rating": 4.7,
        "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
        "opening_time": "06:00",
        "closing_time": "22:00"
    },
    {
        "name": "Fontainhas Latin Quarter",
        "description": "Heritage Portuguese colonial neighborhood in Panaji with brightly painted pastel villas, wrought-iron balconies, bakeries, and art galleries.",
        "city": "Goa",
        "state": "Goa",
        "address": "Panaji, Goa",
        "latitude": 15.4989,
        "longitude": 73.8315,
        "category": "Culture",
        "estimated_duration_hours": 2.0,
        "estimated_cost": 0.0,
        "best_visiting_time": "Morning",
        "suitable_interests": "Culture,Architecture,Photography,Food,History",
        "rating": 4.7,
        "image_url": "https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?w=800&auto=format&fit=crop&q=80",
        "opening_time": "08:00",
        "closing_time": "20:00"
    },

    # --- JAIPUR ---
    {
        "name": "Hawa Mahal (Palace of Winds)",
        "description": "Iconic pink sandstone palace with 953 delicately honeycombed lattice windows, built in 1799 for royal ladies to view the city bazaars.",
        "city": "Jaipur",
        "state": "Rajasthan",
        "address": "Hawa Mahal Rd, Badi Choupad, Jaipur",
        "latitude": 26.9239,
        "longitude": 75.8267,
        "category": "Historical",
        "estimated_duration_hours": 1.5,
        "estimated_cost": 50.0,
        "best_visiting_time": "Morning",
        "suitable_interests": "History,Architecture,Photography,Culture",
        "rating": 4.7,
        "image_url": "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80",
        "opening_time": "09:00",
        "closing_time": "17:00"
    },
    {
        "name": "Amber Fort & Palace",
        "description": "Majestic hillside fort known for artistic Hindu-style elements, yellow sandstone courtyards, and the shimmering Sheesh Mahal mirror palace.",
        "city": "Jaipur",
        "state": "Rajasthan",
        "address": "Devisinghpura, Amer, Jaipur",
        "latitude": 26.9855,
        "longitude": 75.8513,
        "category": "Historical",
        "estimated_duration_hours": 3.0,
        "estimated_cost": 100.0,
        "best_visiting_time": "Morning",
        "suitable_interests": "History,Heritage,Architecture,Sightseeing,Culture",
        "rating": 4.8,
        "image_url": "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?w=800&auto=format&fit=crop&q=80",
        "opening_time": "08:00",
        "closing_time": "17:30"
    },
    {
        "name": "City Palace Jaipur",
        "description": "Spectacular royal residence complex featuring Peacock Courtyard, Mughal-Rajput pavilions, museums of royal costumes, and weapon galleries.",
        "city": "Jaipur",
        "state": "Rajasthan",
        "address": "Tulsi Marg, Gangori Bazaar, Jaipur",
        "latitude": 26.9258,
        "longitude": 75.8236,
        "category": "Historical",
        "estimated_duration_hours": 2.5,
        "estimated_cost": 200.0,
        "best_visiting_time": "Afternoon",
        "suitable_interests": "History,Heritage,Architecture,Culture",
        "rating": 4.6,
        "image_url": "https://images.unsplash.com/photo-1598890777032-bde835ba27c2?w=800&auto=format&fit=crop&q=80",
        "opening_time": "09:30",
        "closing_time": "17:00"
    },
    {
        "name": "Jal Mahal (Water Palace)",
        "description": "Poetic palace floating serenely in the middle of Man Sagar Lake, surrounded by the Aravalli hills, especially stunning when illuminated at twilight.",
        "city": "Jaipur",
        "state": "Rajasthan",
        "address": "Amer Rd, Jal Mahal, Jaipur",
        "latitude": 26.9535,
        "longitude": 75.8462,
        "category": "Sightseeing",
        "estimated_duration_hours": 1.0,
        "estimated_cost": 0.0,
        "best_visiting_time": "Sunset",
        "suitable_interests": "Sightseeing,Photography,Nature,Sunset",
        "rating": 4.5,
        "image_url": "https://images.unsplash.com/photo-1585135497273-1a86b09fe70e?w=800&auto=format&fit=crop&q=80",
        "opening_time": "06:00",
        "closing_time": "22:00"
    },

    # --- BENGALURU ---
    {
        "name": "Vidhana Soudha",
        "description": "Imposing seat of Karnataka legislature built in Neo-Dravidian granite architecture, a signature landmark of the Garden City.",
        "city": "Bengaluru",
        "state": "Karnataka",
        "address": "Dr Ambedkar Rd, Sampangi Rama Nagara, Bengaluru",
        "latitude": 12.9797,
        "longitude": 77.5907,
        "category": "Sightseeing",
        "estimated_duration_hours": 1.0,
        "estimated_cost": 0.0,
        "best_visiting_time": "Evening",
        "suitable_interests": "Sightseeing,Architecture,Photography,History",
        "rating": 4.7,
        "image_url": "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=800&auto=format&fit=crop&q=80",
        "opening_time": "08:00",
        "closing_time": "20:00"
    },
    {
        "name": "Bangalore Palace",
        "description": "Tudor-style royal estate with fortified towers, vintage wood carvings, royal family memorabilia, and sprawling botanical grounds.",
        "city": "Bengaluru",
        "state": "Karnataka",
        "address": "Vasanth Nagar, Bengaluru",
        "latitude": 12.9988,
        "longitude": 77.5921,
        "category": "Historical",
        "estimated_duration_hours": 2.5,
        "estimated_cost": 250.0,
        "best_visiting_time": "Afternoon",
        "suitable_interests": "History,Architecture,Culture,Sightseeing",
        "rating": 4.5,
        "image_url": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80",
        "opening_time": "10:00",
        "closing_time": "17:30"
    },
    {
        "name": "Cubbon Park & Bamboo Groves",
        "description": "300-acre green lung in the heart of Bengaluru, filled with walking paths, historic statues, century-old mahogany trees, and state library.",
        "city": "Bengaluru",
        "state": "Karnataka",
        "address": "Kasturba Rd, Sampangi Rama Nagara, Bengaluru",
        "latitude": 12.9763,
        "longitude": 77.5929,
        "category": "Nature",
        "estimated_duration_hours": 2.0,
        "estimated_cost": 0.0,
        "best_visiting_time": "Morning",
        "suitable_interests": "Nature,Walking,Wellness,Relaxation",
        "rating": 4.6,
        "image_url": "https://images.unsplash.com/photo-1519331379826-f10be5486c6f?w=800&auto=format&fit=crop&q=80",
        "opening_time": "06:00",
        "closing_time": "19:00"
    },
    {
        "name": "Nandi Hills Sunrise Point",
        "description": "Celebrated hilltop fortress 60 km from Bengaluru offering magical sunrise views above sea of clouds, summer retreat of Tipu Sultan.",
        "city": "Bengaluru",
        "state": "Karnataka",
        "address": "Chikkaballapur, Karnataka",
        "latitude": 13.3702,
        "longitude": 77.6835,
        "category": "Adventure",
        "estimated_duration_hours": 3.5,
        "estimated_cost": 30.0,
        "best_visiting_time": "Morning",
        "suitable_interests": "Adventure,Nature,Sunrise,Trekking,Photography",
        "rating": 4.6,
        "image_url": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80",
        "opening_time": "06:00",
        "closing_time": "18:00"
    },

    # --- MUNNAR ---
    {
        "name": "Munnar Tea Plantations & Museum",
        "description": "Endless rolling carpet of emerald tea gardens in the misty Western Ghats, with tea processing demonstrations and tasting sessions.",
        "city": "Munnar",
        "state": "Kerala",
        "address": "Nullatanni, Munnar",
        "latitude": 10.0889,
        "longitude": 77.0595,
        "category": "Nature",
        "estimated_duration_hours": 2.5,
        "estimated_cost": 150.0,
        "best_visiting_time": "Morning",
        "suitable_interests": "Nature,Tea,Sightseeing,Photography,Relaxation",
        "rating": 4.8,
        "image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80",
        "opening_time": "09:00",
        "closing_time": "17:00"
    },
    {
        "name": "Mattupetty Dam & Lake Boating",
        "description": "Picturesque concrete gravity dam surrounded by lush green hills, with speedboat rides and frequent glimpses of wild hill elephants.",
        "city": "Munnar",
        "state": "Kerala",
        "address": "Mattupetty, Munnar",
        "latitude": 10.1060,
        "longitude": 77.1235,
        "category": "Nature",
        "estimated_duration_hours": 2.0,
        "estimated_cost": 100.0,
        "best_visiting_time": "Afternoon",
        "suitable_interests": "Nature,Boating,Sightseeing,Relaxation",
        "rating": 4.5,
        "image_url": "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&auto=format&fit=crop&q=80",
        "opening_time": "09:30",
        "closing_time": "17:00"
    },
    {
        "name": "Eravikulam National Park",
        "description": "High-altitude sanctuary home to the endangered Nilgiri Tahr mountain goat and Anamudi, the highest peak in South India.",
        "city": "Munnar",
        "state": "Kerala",
        "address": "Kannan Devan Hills, Munnar",
        "latitude": 10.2016,
        "longitude": 77.0467,
        "category": "Nature",
        "estimated_duration_hours": 3.0,
        "estimated_cost": 200.0,
        "best_visiting_time": "Morning",
        "suitable_interests": "Nature,Wildlife,Trekking,Photography,Sightseeing",
        "rating": 4.7,
        "image_url": "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&auto=format&fit=crop&q=80",
        "opening_time": "07:30",
        "closing_time": "16:00"
    },

    # --- AGRA ---
    {
        "name": "Taj Mahal",
        "description": "World-renowned ivory-white marble mausoleum on the Yamuna river, an architectural wonder of the world symbolizing eternal love.",
        "city": "Agra",
        "state": "Uttar Pradesh",
        "address": "Dharmapuri, Forest Colony, Tajganj, Agra",
        "latitude": 27.1751,
        "longitude": 78.0421,
        "category": "Historical",
        "estimated_duration_hours": 3.0,
        "estimated_cost": 50.0,
        "best_visiting_time": "Sunrise",
        "suitable_interests": "History,Heritage,Architecture,Sightseeing,Photography",
        "rating": 4.9,
        "image_url": "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&auto=format&fit=crop&q=80",
        "opening_time": "06:00",
        "closing_time": "18:30"
    },
    {
        "name": "Agra Fort",
        "description": "Massive 16th-century red sandstone fortress of Mughal emperors, containing Khas Mahal, Diwan-i-Khas, and iconic distant views of the Taj.",
        "city": "Agra",
        "state": "Uttar Pradesh",
        "address": "Agra Fort, Rakabganj, Agra",
        "latitude": 27.1795,
        "longitude": 78.0211,
        "category": "Historical",
        "estimated_duration_hours": 2.5,
        "estimated_cost": 50.0,
        "best_visiting_time": "Morning",
        "suitable_interests": "History,Architecture,Heritage,Photography",
        "rating": 4.7,
        "image_url": "https://images.unsplash.com/photo-1592635196078-9fdc757f27f4?w=800&auto=format&fit=crop&q=80",
        "opening_time": "06:00",
        "closing_time": "18:00"
    },
    {
        "name": "Mehtab Bagh (Moonlight Garden)",
        "description": "Charbagh garden complex situated opposite the Taj Mahal across the Yamuna River, offering picturesque sunset reflections.",
        "city": "Agra",
        "state": "Uttar Pradesh",
        "address": "Nagla Devjit, Agra",
        "latitude": 27.1800,
        "longitude": 78.0418,
        "category": "Nature",
        "estimated_duration_hours": 1.5,
        "estimated_cost": 25.0,
        "best_visiting_time": "Sunset",
        "suitable_interests": "Nature,Sunset,Photography,Sightseeing,Relaxation",
        "rating": 4.6,
        "image_url": "https://images.unsplash.com/photo-1585135497273-1a86b09fe70e?w=800&auto=format&fit=crop&q=80",
        "opening_time": "06:00",
        "closing_time": "18:00"
    }
]
